from .arrow import ArrowDataSource
from .fake import FakeDataSource
from .github import GithubDataSource
from .googlesheets import GoogleSheetsDataSource
from .huggingface import HuggingFaceDatasets
from .kaggle import KaggleDataSource
from .opensky import OpenSkyDataSource
from .robinhood import RobinhoodDataSource
from .salesforce import SalesforceDataSource
from .simplejson import SimpleJsonDataSource
from .stock import StockDataSource
from .jsonplaceholder import JSONPlaceholderDataSource
from .meta_capi import MetaCapiDataSource
from .sftp import SFTPDataSource
from .jira import JiraDataSource
from .oracle import OracleDataSource
from .notion import NotionDataSource
from .ghibli import GhibliDataSource
from .pokemon import PokemonDataSource
from .advice import AdviceDataSource
from .trivia import TriviaDataSource
from .fakestore import FakeStoreDataSource
from .reqres import ReqresDataSource
from .coindesk import CoinDeskDataSource
from .agify import AgifyDataSource
from .metmuseum import MetMuseumDataSource
from .picsum import PicsumDataSource
