from .arrow import ArrowDataSource
from .fake import FakeDataSource
from .github import GithubDataSource
from .googlesheets import GoogleSheetsDataSource
from .huggingface import HuggingFaceDatasets
from .kaggle import KaggleDataSource
from .opensky import OpenSkyDataSource
from .robinhood import RobinhoodDataSource
from .salesforce import SalesforceDataSource
from .simplejson import SimpleJsonDataSource
from .stock import StockDataSource
from .jsonplaceholder import JSONPlaceholderDataSource
from .meta_capi import MetaCapiDataSource
from .sftp import SFTPDataSource
from .jira import JiraDataSource
from .oracle import OracleDataSource
from .notion import NotionDataSource
from .dog import DogDataSource
from .quotable import QuotableDataSource
from .bored import BoredDataSource
from .universities import UniversitiesDataSource
from .cocktail import CocktailDataSource
from .yamlfile import YamlFileDataSource
from .tomlfile import TomlFileDataSource
from .jsonlines import JsonLinesDataSource
from .httpbin import HttpbinDataSource
from .ipapi import IpApiDataSource
