from .arrow import ArrowDataSource
from .fake import FakeDataSource
from .github import GithubDataSource
from .googlesheets import GoogleSheetsDataSource
from .huggingface import HuggingFaceDatasets
from .kaggle import KaggleDataSource
from .opensky import OpenSkyDataSource
from .robinhood import RobinhoodDataSource
from .salesforce import SalesforceDataSource
from .simplejson import SimpleJsonDataSource
from .stock import StockDataSource
from .jsonplaceholder import JSONPlaceholderDataSource
from .meta_capi import MetaCapiDataSource
from .sftp import SFTPDataSource
from .jira import JiraDataSource
from .oracle import OracleDataSource
from .notion import NotionDataSource
from .azuregraph import AzureGraphDataSource
